/**:
  ros__parameters:
    global_thread_num: 2
    local_thread_num: 1
    online: true
#    action_list:
#      - name: "forward"
#        onestep_forward_m: "0.3"
#        onestep_rotation_deg: "0.0"
#      - name: "back"
#        onestep_forward_m: "-0.2"
#        onestep_rotation_deg: "0.0"
#      - name: "right"
#        onestep_forward_m: "0.0"
#        onestep_rotation_deg: "-20.0"
#      - name: "rightfw"
#        onestep_forward_m: "0.2"
#        onestep_rotation_deg: "-20.0"
#      - name: "left"
#        onestep_forward_m: "0.0"
#        onestep_rotation_deg: "20.0"
#      - name: "leftfw"
#        onestep_forward_m: "0.2"
#        onestep_rotation_deg: "20.0"
