/**:
  ros__parameters:
    global_thread_num: 2
    local_thread_num: 1
    online: true
    theta_cell_num: 60
    gthread_num: 8
    gsafety_radius: 0.2
    gsafety_radius_penalty: 100000
    ggoal_margin_radius: 0.3
    ggoal_margin_theta: 15
    gmap_type: occupancy
#    action_list:
#      - name: "forward"
#        onestep_forward_m: "0.3"
#        onestep_rotation_deg: "0.0"
#      - name: "back"
#        onestep_forward_m: "-0.2"
#        onestep_rotation_deg: "0.0"
#      - name: "right"
#        onestep_forward_m: "0.0"
#        onestep_rotation_deg: "-20.0"
#      - name: "rightfw"
#        onestep_forward_m: "0.2"
#        onestep_rotation_deg: "-20.0"
#      - name: "left"
#        onestep_forward_m: "0.0"
#        onestep_rotation_deg: "20.0"
#      - name: "leftfw"
#        onestep_forward_m: "0.2"
#        onestep_rotation_deg: "20.0"
